[package]
name = "logfmt"
version = "0.1.0"
authors = ["Alexey Aristov <aav@suprematic.de>"]
edition = "2018"

[dependencies]
ansi_term = "0.12"
chrono = "0.4"
serde_json = "1.0"
colored_json = "2.1"
atty = "0.2.14"
